### ISSUE TITLE
What is Q in the latent encoder layers?

### ISSUE THREAD

**Issue by zhangyuygss** [krasserm/perceiver-io#2]
It seems that in the multi-layer [encoder](https://github.com/krasserm/perceiver-io/blob/main/perceiver/model.py#L187), you use `x_latent` as `Q`, `x` as `KV`, shouldn't the `QKV` all be `x_latent` in latent layers?
Please correct me if I  missed something in the paper, thank you!

**Comment by krasserm** [comment]
The layer you referenced is a [sequence of 1 cross-attention layer and a block of n self-attention layers](https://github.com/krasserm/perceiver-io/blob/fb818b1763f61e259b23b8b014df2ac01c303a54/perceiver/model.py#L151-L159). The block of self-attention layers is called *Latent Transformer* in Fig. 1 of the [paper](https://arxiv.org/abs/2103.03206). It uses `x_latent` as `QKV`. Only the cross-attention layer uses `x` as `KV` and `x_latent` as `Q`.
