### ISSUE TITLE
Multimodal autoencoder

### ISSUE THREAD

**Issue by lantiga** [krasserm/perceiver-io#52]
Hi @krasserm, awesome project BTW.
I'd be interested in implementing the multimodal autoencoder in the perceiver-io paper. Are there any existing efforts along this lines on our end, or do you have any suggestions before starting?

**Comment by lantiga** [comment]
Thank you @krasserm for the directions! We'll reach back if we find roadblocks and possibly contribute the implementation if it works out.

**Comment by ricard-inho** [comment]
@lantiga Do you have an implementation for multimodal autoencoder?
