### ISSUE TITLE
AttributeError: 'tuple' object has no attribute 'last_hidden_state'

### ISSUE THREAD

**Issue by martin-minovski** [krasserm/perceiver-io#56]
Hi and thanks for sharing this repo. I'm trying to run the symbolic music audio model training examples and they run fine with activation checkpointing disabled, however if I enable that, I get:

AttributeError: 'tuple' object has no attribute 'last_hidden_state'

Dumping the output of ca_output in perceiver/model/core/modules.py produces a proper ModuleOutput object on the sanity checks but when it starts training, just a ('last_hidden_state', 'kv_cache') tuple.

**Comment by cstub** [comment]
Thanks for bringing this to our attention. I can reproduce the problem and work on a fix.
